[package]
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
license = "Apache-2.0"
name = "tests"
version = "0.0.0"

[dependencies]
fuels = { version = "0.33", features = ["fuel-core-lib"] }
tokio = { version = "1.15", features = ["rt", "macros"] }
test_helpers = { path = "../test_helpers" }

[[test]]
harness = true
name = "harness"
path = "tests/harness.rs"
